### ISSUE TITLE
Silicon chip macs not compatible with current baseos build

### ISSUE THREAD

**Issue by glemieux** [NGEET/tutorial-containers#11]
> 3. I am on a Mac M3 - Sonoma 14.3
When I rerun "docker compose up -d" I no longer get the error message above, I get a new error (image below) with the error message: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
![image](https://github.com/user-attachments/assets/16830b78-f837-4430-a6e8-89c4147fc660)

_Originally posted by @colettembrown in https://github.com/NGEET/fates-tutorial/discussions/37#discussioncomment-10433753_

**Comment by glemieux** [comment]
Reference for building multi-platform images: https://docs.docker.com/build/building/multi-platform/

**Comment by glemieux** [comment]
Tagging @annaspiers as she ran into the same issue.

**Comment by glemieux** [comment]
FYI @colettembrown, I may have a fix for this soon.  I'm borrowing an Apple silicon macbook tomorrow to rebuild the images for that architecture.

**Comment by glemieux** [comment]
New baseos mage built successfully.  Rebuilding all images for the arm64 architecture.

Note for posterity: I had to use the "hard way" of building a manifest for docker hub to make sure that it will automatically download the correct image by architecture: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by annaspiers** [comment]
I pulled the updated development branch of fates-tutorial and ran `docker compose up -d` successfully. Nice!
<img width="616" alt="Screenshot 2024-08-28 at 11 15 54 AM" src="https://github.com/user-attachments/assets/4deb5b18-3515-4e73-910c-f47223981d04">

**Comment by glemieux** [comment]
I've built `arm64` versions of the  docker images using a loaned M1 macbook.  For future development this should be handled by an online build process (e.g. docker cloud or github actions).  See #13
